### ISSUE TITLE
'potrace._potrace.Bitmap' object has no attribute 'to_xml'

### ISSUE THREAD

**Issue by Ravindra-Kanitkar** [mehdidc/pixel_to_svg#1]
Hey, your repo looks perfect but it has one problem! While running the potrace step, to_xml() method is not there! Please tell me how to tackle it?

**Comment by mehdidc** [comment]
Hey! thanks for your interest and for noticing this, I forgot to point it out, will do, you need to use the branch "to_xml" branch from here: https://github.com/gungoren/pypotrace/tree/to_xml

**Comment by mehdidc** [comment]
I  remember having a bug and I needed to change a minor thing in that branch, if it does not work, please try my fork https://github.com/mehdidc/pypotrace/tree/to_xml

**Comment by Ravindra-Kanitkar** [comment]
Hey can you list down the steps from start to end installation procedure! I have installed correctly, but I am having problems with pypotrace! I am using linux only, so please can you demonstrate me! Thank You in advance!

**Comment by mehdidc** [comment]
Hey, I realize I forgot to commit my change to the to_xml branch  in my fork,  I did now.
I just tried now the following steps and the example  (https://github.com/mehdidc/pixel_to_svg/blob/master/examples/simple.py) worked fine:

- `sudo apt-get install build-essential python-dev libagg-dev libpotrace-dev pkg-config`
- `git clone https://github.com/mehdidc/pypotrace`
- `cd pypotrace`
- `git checkout  to_xml`
- `rm -fr build/;rm potrace/*.c potrace/*.cpp potrace/agg/*.cpp potrace/*.so potrace/agg/*.so`
- `pip install .`

**Comment by Ravindra-Kanitkar** [comment]
Thanks for your help! It works perfect👍
